version: "3.9"
services:
  ui:
    container_name: ui
    build:
      context: ./ui
      dockerfile: Dockerfile
    image: ui
    restart: always
    environment:
      - REACT_APP_HOST_IP_ADDRESS=http://localhost:8080
    ports:
      - 3000:80
    depends_on:
      - server
    networks:
      - poc

  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - postgres__Host=postgres
    depends_on:
      - postgres
    networks:
      - poc

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_PASSWORD: "Pass1234!"
    networks:
      - poc

networks:
  poc:
    driver: bridge
