version: "3.9"
services:
  server:
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    image: server
    restart: always
    ports:
      - 8080:8080
    expose:
      - 8080
    environment:
      - postgres__Host=postgres
    depends_on:
      - postgres
    networks:
      - poc
    extra_hosts:
      - "host.docker.internal:host-gateway"

  postgres:
    image: "postgres:latest"
    ports:
      - "5432:5432"
    command: postgres -c 'max_connections=500'
    environment:
      POSTGRES_PASSWORD: "Pass1234!"
    networks:
      - poc

  redis:
    image: redis:latest
    command: redis-server --requirepass Pass1234!
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "1"
          memory: 2000M
    restart: on-failure
    ports:
      - "6379:6379"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      - poc

networks:
  poc:
    driver: bridge
